//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        Foo: {
            name: "Foo",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                data1: {
                    name: "data1",
                    type: "Json",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
