import { withOmit } from './omit';
import { withPassword } from './password';
import { withPolicy, WithPolicyContext } from './policy';
import { ModelMeta, PolicyDef } from './types';

/**
 * Gets a Prisma client enhanced with all essential behaviors, including access
 * policy, field validation, field omission and password hashing.
 *
 * It's a shortcut for calling withOmit(withPassword(withPolicy(prisma, options))).
 *
 * @param prisma The Prisma client to enhance.
 * @param context The context to for evaluating access policies.
 * @param policy The access policy data, generated by @zenstack/access-policy plugin.
 * You only need to pass it if you configured the plugin to generate into custom location.
 * @param modelMeta The model metadata, generated by @zenstack/model-meta plugin.
 * You only need to pass it if you configured the plugin to generate into custom location.
 */
export function withPresets<DbClient extends object>(
    prisma: DbClient,
    context?: WithPolicyContext,
    policy?: PolicyDef,
    modelMeta?: ModelMeta
) {
    return withPolicy(withOmit(withPassword(prisma, modelMeta), modelMeta), context, policy, modelMeta);
}
