import type { DataField } from '@zenstackhq/language/ast';
import {
    getDefaultValue,
    getFieldAttributes,
    getFieldTypeName,
    getRelativeSourcePath,
    isFieldRequired,
    stripCommentPrefix,
} from '../extractors';
import type { DocMeta, GenerationContext, Navigation, RenderOptions } from '../types';

interface SectionMeta {
    emoji: string;
    description?: string;
}

const SECTION_META: Record<string, SectionMeta> = {
    'Mixins': { emoji: '🧩', description: 'Reusable field groups mixed into this model.' },
    'Fields': { emoji: '📋', description: 'All fields defined on this entity, including inherited fields from mixins and parent models.' },
    'Relationships': { emoji: '🔗', description: 'Foreign key relationships to other models in the schema.' },
    'Access Policies': { emoji: '🔐', description: 'ZenStack access control rules that determine who can read, create, update, or delete records.' },
    'Indexes': { emoji: '📇', description: 'Database indexes defined on this model for query performance.' },
    'Validation Rules': { emoji: '✅', description: 'Field-level and model-level validation constraints enforced at the ORM layer.' },
    'Used in Procedures': { emoji: '⚡', description: 'Procedures that reference this entity as a parameter or return type.' },
    'Values': { emoji: '🏷️', description: 'Possible values for this enumeration.' },
    'Used By': { emoji: '📍', description: 'Models and fields that reference this type.' },
    'Parameters': { emoji: '📥', description: 'Input parameters accepted by this procedure.' },
    'Returns': { emoji: '📤', description: 'The return type of this procedure.' },
    'References': { emoji: '📚' },
};

/** Returns a level-2 heading with an inline anchor, emoji prefix, and optional description for the given section name. */
export function sectionHeading(name: string): string[] {
    const meta = SECTION_META[name];
    const emoji = meta?.emoji ?? '';
    const anchor = name.toLowerCase().replace(/\s+/g, '-');
    const prefix = emoji ? `${emoji} ` : '';
    const lines = [`<a id="${anchor}"></a>`, '', `## ${prefix}${name}`];
    if (meta?.description) {
        lines.push('', `> ${meta.description}`);
    }
    return lines;
}

/** Renders the auto-generated header banner with optional source file and generation date. */
export function generatedHeader(ctx?: GenerationContext): string[] {
    const metaParts: string[] = [];
    if (ctx?.schemaFile) metaParts.push(`Source: ${ctx.schemaFile}`);
    if (ctx) metaParts.push(`Generated: ${ctx.generatedAt}`);
    const metaLine = metaParts.length > 0 ? metaParts.join(' · ') : '';

    const contentLines = [
        'DO NOT MODIFY THIS FILE',
        'This file is automatically generated by ZenStack CLI and should not be manually updated.',
    ];
    if (metaLine) contentLines.push(metaLine);

    const maxLen = Math.max(...contentLines.map((l) => l.length));
    const border = '/'.repeat(maxLen + 6);
    const padded = contentLines.map((l) => `// ${l.padEnd(maxLen)} //`);

    return ['```', border, ...padded, border, '```', ''];
}

/** Renders an Index / Category / Entity breadcrumb trail. */
export function breadcrumbs(
    entityType: 'Models' | 'Views' | 'Enums' | 'Types' | 'Procedures',
    entityName: string,
    prefix: string,
): string {
    const anchor = entityType.toLowerCase();
    return `[Index](${prefix}index.md) / [${entityType}](${prefix}index.md#${anchor}) / \`${entityName}\``;
}

/** Renders previous/next navigation links at the bottom of entity pages. */
export function navigationFooter(nav: Navigation | undefined): string[] {
    if (!nav) return [];
    const parts: string[] = [];
    if (nav.prev) parts.push(`Previous: [${nav.prev.name}](${nav.prev.path})`);
    if (nav.next) parts.push(`Next: [${nav.next.name}](${nav.next.path})`);
    if (parts.length === 0) return [];
    return ['---', '', parts.join(' · '), ''];
}

const ZENSTACK_DOCS_BASE = 'https://zenstack.dev/docs/reference/zmodel';

const ENTITY_DOC_PATHS: Record<string, string> = {
    model: `${ZENSTACK_DOCS_BASE}/model`,
    enum: `${ZENSTACK_DOCS_BASE}/enum`,
    type: `${ZENSTACK_DOCS_BASE}/type`,
    view: `${ZENSTACK_DOCS_BASE}/view`,
    procedure: 'https://zenstack.dev/docs/category/reference',
};

/** Renders a "References" section linking to the official ZenStack documentation for the entity type. */
export function referencesSection(entityType: 'model' | 'enum' | 'type' | 'view' | 'procedure'): string[] {
    const url = ENTITY_DOC_PATHS[entityType];
    if (!url) return [];
    return [
        '---', '',
        ...sectionHeading('References'), '',
        `- [ZModel ${entityType}s — ZenStack documentation](${url})`,
        '',
    ];
}

/** Renders a collapsible `<details>` block containing the raw ZModel declaration and optional source path. */
export function declarationBlock(cstText: string | undefined, sourcePath: string | undefined): string[] {
    if (!cstText) return [];
    const stripped = cstText
        .split('\n')
        .filter((line) => !line.trim().startsWith('///'))
        .join('\n');
    const summaryLabel = sourcePath ? `Declaration · <code>${sourcePath}</code>` : 'Declaration';
    return [
        '<details>',
        `<summary>${summaryLabel}</summary>`,
        '',
        '```prisma',
        stripped,
        '```',
        '',
        '</details>',
        '',
    ];
}

/** Renders a blockquoted description from doc-comments. */
export function renderDescription(comments: string[]): string[] {
    const description = stripCommentPrefix(comments);
    if (!description) return [];
    const lines: string[] = [];
    for (const line of description.split('\n')) {
        lines.push(`> ${line}`);
    }
    lines.push('');
    return lines;
}

/** Renders category, since, deprecated, table mapping, and source path metadata as a single line. */
export function renderMetadata(
    docMeta: DocMeta,
    sourcePath: string | undefined,
    extra?: { mappedTable?: string; dbSchema?: string },
): string[] {
    const parts: string[] = [];
    if (docMeta.category) parts.push(`**Category:** ${docMeta.category}`);
    if (docMeta.since) parts.push(`**Since:** ${docMeta.since}`);
    if (docMeta.deprecated) parts.push(`**Deprecated:** ${docMeta.deprecated}`);
    if (extra?.mappedTable) parts.push(`**Table:** \`${extra.mappedTable}\``);
    if (extra?.dbSchema) parts.push(`**Schema:** \`${extra.dbSchema}\``);
    if (sourcePath) parts.push(`**Defined in:** \`${sourcePath}\``);
    if (parts.length === 0) return [];
    return [parts.join(' · '), ''];
}

/** Builds a `Map<name, Navigation>` with prev/next links for a sorted list of entity names. */
export function buildNavList(
    sortedNames: string[],
    pathPrefix: string,
): Map<string, Navigation> {
    const navMap = new Map<string, Navigation>();
    for (let i = 0; i < sortedNames.length; i++) {
        const current = sortedNames[i]!;
        const nav: Navigation = {};
        if (i > 0) {
            const prev = sortedNames[i - 1]!;
            nav.prev = { name: prev, path: `${pathPrefix}${prev}.md` };
        }
        if (i < sortedNames.length - 1) {
            const next = sortedNames[i + 1]!;
            nav.next = { name: next, path: `${pathPrefix}${next}.md` };
        }
        navMap.set(current, nav);
    }
    return navMap;
}

// ── Shared section renderers ────────────────────────────────────────────

/** Returns fields in declaration or alphabetical order. */
export function orderFields(fields: DataField[], order: RenderOptions['fieldOrder']): DataField[] {
    return order === 'alphabetical'
        ? [...fields].sort((a, b) => a.name.localeCompare(b.name))
        : [...fields];
}

/** Renders a 6-column fields table (no Source column). Used by type-page and view-page. */
export function renderSimpleFieldsTable(fields: DataField[]): string[] {
    if (fields.length === 0) return [];
    const lines = [
        ...sectionHeading('Fields'), '',
        '| Field | Type | Required | Default | Attributes | Description |',
        '| --- | --- | --- | --- | --- | --- |',
    ];
    for (const field of fields) {
        const fieldDescription = stripCommentPrefix(field.comments) || '—';
        const fieldAnchor = `<a id="field-${field.name}"></a>`;
        lines.push(
            `| ${fieldAnchor}\`${field.name}\` | ${getFieldTypeName(field, false)} | ${isFieldRequired(field) ? 'Yes' : 'No'} | ${getDefaultValue(field)} | ${getFieldAttributes(field)} | ${fieldDescription} |`,
        );
    }
    lines.push('');
    return lines;
}

/** Renders "Defined in" line + collapsible declaration block. Used by enum, type, and procedure pages. */
export function renderSourceAndDeclaration(
    node: Parameters<typeof getRelativeSourcePath>[0] & { $cstNode?: { text?: string } },
    schemaDir: string | undefined,
): string[] {
    const sourcePath = getRelativeSourcePath(node, schemaDir);
    const lines: string[] = [];
    if (sourcePath) {
        lines.push(`**Defined in:** \`${sourcePath}\``, '');
    }
    lines.push(...declarationBlock(node.$cstNode?.text, sourcePath));
    return lines;
}
