//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                role: {
                    name: "role",
                    type: "Role"
                },
                address: {
                    name: "address",
                    type: "Address",
                    optional: true,
                    attributes: [{ name: "@json" }]
                },
                posts: {
                    name: "posts",
                    type: "Post",
                    array: true,
                    relation: { opposite: "owner" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                title: {
                    name: "title",
                    type: "String"
                },
                owner: {
                    name: "owner",
                    type: "User",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "posts", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "owner"
                    ]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Address: {
            name: "Address",
            fields: {
                street: {
                    name: "street",
                    type: "String"
                },
                city: {
                    name: "city",
                    type: "String"
                },
                zip: {
                    name: "zip",
                    type: "String",
                    optional: true
                }
            }
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                ADMIN: "ADMIN",
                USER: "USER"
            }
        }
    } as const;
    authType = "User" as const;
    procedures = {
        getUserPosts: {
            params: {
                userId: { name: "userId", type: "String" }
            },
            returnType: "Post",
            returnArray: true
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
