//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        Foo: {
            name: "Foo",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    typeDefs = {
        Permission: {
            name: "Permission",
            fields: {
                actionCode: {
                    name: "actionCode",
                    type: "String"
                }
            }
        },
        Auth: {
            name: "Auth",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                permissions: {
                    name: "permissions",
                    type: "Permission",
                    array: true
                },
                role: {
                    name: "role",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@auth" }
            ] as readonly AttributeApplication[]
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
