//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                profile: {
                    name: "profile",
                    type: "Profile",
                    attributes: [{ name: "@json" }]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    typeDefs = {
        Profile: {
            name: "Profile",
            fields: {
                age: {
                    name: "age",
                    type: "Int"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                gender: {
                    name: "gender",
                    type: "Gender",
                    optional: true
                },
                jobs: {
                    name: "jobs",
                    type: "Job",
                    array: true
                },
                address: {
                    name: "address",
                    type: "Address",
                    optional: true
                },
                tags: {
                    name: "tags",
                    type: "String",
                    optional: true,
                    array: true
                }
            }
        },
        Address: {
            name: "Address",
            fields: {
                country: {
                    name: "country",
                    type: "String"
                },
                zip: {
                    name: "zip",
                    type: "String",
                    optional: true
                }
            }
        },
        Job: {
            name: "Job",
            fields: {
                title: {
                    name: "title",
                    type: "String"
                }
            }
        }
    } as const;
    enums = {
        Gender: {
            name: "Gender",
            values: {
                MALE: "MALE",
                FEMALE: "FEMALE"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
