//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                email: {
                    name: "email",
                    type: "String",
                    attributes: [{ name: "@email" }, { name: "@meta", args: [{ name: "name", value: ExpressionUtils.literal("description") }, { name: "value", value: ExpressionUtils.literal("The user's email address") }] }]
                },
                username: {
                    name: "username",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(3) }, { name: "max", value: ExpressionUtils.literal(50) }] }]
                },
                website: {
                    name: "website",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }]
                },
                code: {
                    name: "code",
                    type: "String",
                    attributes: [{ name: "@startsWith", args: [{ name: "text", value: ExpressionUtils.literal("USR") }] }]
                },
                age: {
                    name: "age",
                    type: "Int",
                    attributes: [{ name: "@gt", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }, { name: "@lte", args: [{ name: "value", value: ExpressionUtils.literal(150) }] }]
                },
                score: {
                    name: "score",
                    type: "Float",
                    attributes: [{ name: "@gte", args: [{ name: "value", value: ExpressionUtils.literal(0.0) }] }, { name: "@lt", args: [{ name: "value", value: ExpressionUtils.literal(100.0) }] }]
                },
                bigNum: {
                    name: "bigNum",
                    type: "BigInt",
                    attributes: [{ name: "@gte", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }]
                },
                balance: {
                    name: "balance",
                    type: "Decimal",
                    attributes: [{ name: "@gt", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }]
                },
                active: {
                    name: "active",
                    type: "Boolean"
                },
                birthdate: {
                    name: "birthdate",
                    type: "DateTime",
                    optional: true
                },
                avatar: {
                    name: "avatar",
                    type: "Bytes",
                    optional: true
                },
                metadata: {
                    name: "metadata",
                    type: "Json",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "Status"
                },
                address: {
                    name: "address",
                    type: "Address",
                    optional: true,
                    attributes: [{ name: "@json" }]
                },
                posts: {
                    name: "posts",
                    type: "Post",
                    array: true,
                    relation: { opposite: "author" }
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.field("age"), ">=", ExpressionUtils.literal(18)) }, { name: "message", value: ExpressionUtils.literal("Must be adult") }, { name: "path", value: ExpressionUtils.array("String", [ExpressionUtils.literal("age")]) }] },
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("description") }, { name: "value", value: ExpressionUtils.literal("A user of the system") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                title: {
                    name: "title",
                    type: "String"
                },
                published: {
                    name: "published",
                    type: "Boolean"
                },
                author: {
                    name: "author",
                    type: "User",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("authorId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "posts", fields: ["authorId"], references: ["id"] }
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "author"
                    ]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Product: {
            name: "Product",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                price: {
                    name: "price",
                    type: "Float"
                },
                discount: {
                    name: "discount",
                    type: "Float",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                finalPrice: {
                    name: "finalPrice",
                    type: "Float",
                    attributes: [{ name: "@computed" }],
                    computed: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            computedFields: {
                finalPrice(_context: {
                    modelAlias: string;
                }): number {
                    throw new Error("This is a stub for computed field");
                }
            }
        },
        Asset: {
            name: "Asset",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                assetType: {
                    name: "assetType",
                    type: "String",
                    isDiscriminator: true
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("assetType") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            },
            isDelegate: true,
            subModels: ["Video", "Image"]
        },
        Video: {
            name: "Video",
            baseModel: "Asset",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Asset",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                assetType: {
                    name: "assetType",
                    type: "String",
                    originModel: "Asset",
                    isDiscriminator: true
                },
                duration: {
                    name: "duration",
                    type: "Int"
                },
                url: {
                    name: "url",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Image: {
            name: "Image",
            baseModel: "Asset",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Asset",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                assetType: {
                    name: "assetType",
                    type: "String",
                    originModel: "Asset",
                    isDiscriminator: true
                },
                format: {
                    name: "format",
                    type: "String"
                },
                width: {
                    name: "width",
                    type: "Int"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    typeDefs = {
        Address: {
            name: "Address",
            fields: {
                street: {
                    name: "street",
                    type: "String",
                    attributes: [{ name: "@meta", args: [{ name: "name", value: ExpressionUtils.literal("description") }, { name: "value", value: ExpressionUtils.literal("Street address line") }] }]
                },
                city: {
                    name: "city",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(2) }] }]
                },
                zip: {
                    name: "zip",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("zip"), "==", ExpressionUtils._null()), "||", ExpressionUtils.binary(ExpressionUtils.call("length", [ExpressionUtils.field("zip")]), "==", ExpressionUtils.literal(5))) }, { name: "message", value: ExpressionUtils.literal("Zip code must be exactly 5 characters") }, { name: "path", value: ExpressionUtils.array("String", [ExpressionUtils.literal("zip")]) }] },
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("description") }, { name: "value", value: ExpressionUtils.literal("A mailing address") }] }
            ]
        }
    } as const;
    enums = {
        Status: {
            name: "Status",
            values: {
                ACTIVE: "ACTIVE",
                INACTIVE: "INACTIVE",
                PENDING: "PENDING"
            },
            attributes: [
                { name: "@@meta", args: [{ name: "name", value: ExpressionUtils.literal("description") }, { name: "value", value: ExpressionUtils.literal("User account status") }] }
            ]
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
