//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Item = $ModelResult<$Schema, "Item">;
export type GeoRecord = $ModelResult<$Schema, "GeoRecord">;
export type GeoRecordWithDefault = $ModelResult<$Schema, "GeoRecordWithDefault">;
