//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Account = $ModelResult<$Schema, "Account">;
export type User = $ModelResult<$Schema, "User">;
export type VerificationToken = $ModelResult<$Schema, "VerificationToken">;
export type Session = $ModelResult<$Schema, "Session">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Poll = $ModelResult<$Schema, "Poll">;
export type Watcher = $ModelResult<$Schema, "Watcher">;
export type Participant = $ModelResult<$Schema, "Participant">;
export type Option = $ModelResult<$Schema, "Option">;
export type Vote = $ModelResult<$Schema, "Vote">;
export type Comment = $ModelResult<$Schema, "Comment">;
export type PollView = $ModelResult<$Schema, "PollView">;
export type Space = $ModelResult<$Schema, "Space">;
export type SpaceMember = $ModelResult<$Schema, "SpaceMember">;
export type SpaceMemberInvite = $ModelResult<$Schema, "SpaceMemberInvite">;
export type Subscription = $ModelResult<$Schema, "Subscription">;
export type PaymentMethod = $ModelResult<$Schema, "PaymentMethod">;
export type ScheduledEvent = $ModelResult<$Schema, "ScheduledEvent">;
export type RescheduledEventDate = $ModelResult<$Schema, "RescheduledEventDate">;
export type ScheduledEventInvite = $ModelResult<$Schema, "ScheduledEventInvite">;
export type Credential = $ModelResult<$Schema, "Credential">;
export type CalendarConnection = $ModelResult<$Schema, "CalendarConnection">;
export type ProviderCalendar = $ModelResult<$Schema, "ProviderCalendar">;
export type InstanceSettings = $ModelResult<$Schema, "InstanceSettings">;
export type License = $ModelResult<$Schema, "License">;
export type LicenseValidation = $ModelResult<$Schema, "LicenseValidation">;
export type InstanceLicense = $ModelResult<$Schema, "InstanceLicense">;
export const TimeFormat = $schema.enums.TimeFormat.values;
export type TimeFormat = (typeof TimeFormat)[keyof typeof TimeFormat];
export const UserRole = $schema.enums.UserRole.values;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
export const ParticipantVisibility = $schema.enums.ParticipantVisibility.values;
export type ParticipantVisibility = (typeof ParticipantVisibility)[keyof typeof ParticipantVisibility];
export const PollStatus = $schema.enums.PollStatus.values;
export type PollStatus = (typeof PollStatus)[keyof typeof PollStatus];
export const VoteType = $schema.enums.VoteType.values;
export type VoteType = (typeof VoteType)[keyof typeof VoteType];
export const SpaceMemberRole = $schema.enums.SpaceMemberRole.values;
export type SpaceMemberRole = (typeof SpaceMemberRole)[keyof typeof SpaceMemberRole];
export const SpaceTier = $schema.enums.SpaceTier.values;
export type SpaceTier = (typeof SpaceTier)[keyof typeof SpaceTier];
export const SubscriptionStatus = $schema.enums.SubscriptionStatus.values;
export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];
export const SubscriptionInterval = $schema.enums.SubscriptionInterval.values;
export type SubscriptionInterval = (typeof SubscriptionInterval)[keyof typeof SubscriptionInterval];
export const ScheduledEventStatus = $schema.enums.ScheduledEventStatus.values;
export type ScheduledEventStatus = (typeof ScheduledEventStatus)[keyof typeof ScheduledEventStatus];
export const ScheduledEventInviteStatus = $schema.enums.ScheduledEventInviteStatus.values;
export type ScheduledEventInviteStatus = (typeof ScheduledEventInviteStatus)[keyof typeof ScheduledEventInviteStatus];
export const CredentialType = $schema.enums.CredentialType.values;
export type CredentialType = (typeof CredentialType)[keyof typeof CredentialType];
export const LicenseType = $schema.enums.LicenseType.values;
export type LicenseType = (typeof LicenseType)[keyof typeof LicenseType];
export const LicenseStatus = $schema.enums.LicenseStatus.values;
export type LicenseStatus = (typeof LicenseStatus)[keyof typeof LicenseStatus];
