import fs from 'node:fs';
import path from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { findFieldLine, generateFromSchema, readDoc } from '../utils';

describe('documentation plugin: common features', () => {
    describe('header, breadcrumbs, and badges', () => {
        let tmpDir: string;
        beforeAll(async () => {
            tmpDir = await generateFromSchema(`
                enum Role { ADMIN MEMBER }
                type Timestamps {
                    createdAt DateTime @default(now())
                }
                model User {
                    id   String @id @default(cuid())
                    role Role
                    posts Post[]
                }
                model Post {
                    id       String @id @default(cuid())
                    author   User   @relation(fields: [authorId], references: [id])
                    authorId String
                }
                procedure getUser(id: String): User
                mutation procedure signUp(name: String): User
            `);
        });

        it('all pages include auto-generated header with do-not-edit warning', () => {
            const headerPattern = /DO NOT MODIFY THIS FILE/;
            expect(readDoc(tmpDir, 'index.md')).toMatch(headerPattern);
            expect(readDoc(tmpDir, 'models', 'User.md')).toMatch(headerPattern);
            expect(readDoc(tmpDir, 'enums', 'Role.md')).toMatch(headerPattern);
            expect(readDoc(tmpDir, 'types', 'Timestamps.md')).toMatch(headerPattern);
            expect(readDoc(tmpDir, 'procedures', 'getUser.md')).toMatch(headerPattern);
            expect(readDoc(tmpDir, 'relationships.md')).toMatch(headerPattern);
        });

        it('header uses comment-block banner style without [!CAUTION]', () => {
            const indexContent = readDoc(tmpDir, 'index.md');
            expect(indexContent).toContain('// DO NOT MODIFY THIS FILE');
            expect(indexContent).toContain('// This file is automatically generated');
            expect(indexContent).not.toContain('[!CAUTION]');

            const userDoc = readDoc(tmpDir, 'models', 'User.md');
            expect(userDoc).toContain('// DO NOT MODIFY THIS FILE');
            expect(userDoc).not.toContain('[!CAUTION]');
        });

        it('entity pages show breadcrumb navigation and type badges', () => {
            const userDoc = readDoc(tmpDir, 'models', 'User.md');
            expect(userDoc).toContain('[Index](../index.md)');
            expect(userDoc).toContain('[Models](../index.md#models)');
            expect(userDoc).toContain('<kbd>Model</kbd>');

            const roleDoc = readDoc(tmpDir, 'enums', 'Role.md');
            expect(roleDoc).toContain('[Enums](../index.md#enums)');
            expect(roleDoc).toContain('<kbd>Enum</kbd>');

            const tsDoc = readDoc(tmpDir, 'types', 'Timestamps.md');
            expect(tsDoc).toContain('[Types](../index.md#types)');
            expect(tsDoc).toContain('<kbd>Type</kbd>');

            const queryDoc = readDoc(tmpDir, 'procedures', 'getUser.md');
            expect(queryDoc).toContain('[Procedures](../index.md#procedures)');
            expect(queryDoc).toContain('<kbd>Query</kbd>');

            const mutDoc = readDoc(tmpDir, 'procedures', 'signUp.md');
            expect(mutDoc).toContain('<kbd>Mutation</kbd>');
        });
    });

    it('header includes schema file path and generation date', async () => {
        const tmpDir = await generateFromSchema(`
            model User {
                id String @id @default(cuid())
            }
        `, {}, '/app/zenstack/schema.zmodel');

        const indexContent = readDoc(tmpDir, 'index.md');
        expect(indexContent).toContain('schema.zmodel');
        expect(indexContent).toMatch(/Generated.*\d{4}-\d{2}-\d{2}/);

        const userDoc = readDoc(tmpDir, 'models', 'User.md');
        expect(userDoc).toContain('schema.zmodel');
        expect(userDoc).toMatch(/Generated.*\d{4}-\d{2}-\d{2}/);
    });

    it('produces correct directory structure for models and enums', async () => {
        const tmpDir = await generateFromSchema(`
            model User {
                id   String @id @default(cuid())
                role Role
            }
            model Post {
                id String @id @default(cuid())
            }
            enum Role {
                ADMIN
                USER
            }
        `);

        expect(fs.existsSync(path.join(tmpDir, 'index.md'))).toBe(true);
        expect(fs.existsSync(path.join(tmpDir, 'models', 'User.md'))).toBe(true);
        expect(fs.existsSync(path.join(tmpDir, 'models', 'Post.md'))).toBe(true);
        expect(fs.existsSync(path.join(tmpDir, 'enums', 'Role.md'))).toBe(true);
    });

    it('omits sections when include* flags are false', async () => {
        const tmpDir = await generateFromSchema(`
            model User {
                id    String @id @default(cuid())
                email String @email
                posts Post[]
                @@allow('read', true)
                @@index([email])
            }
            model Post {
                id       String @id @default(cuid())
                author   User   @relation(fields: [authorId], references: [id])
                authorId String
            }
        `, {
            includeRelationships: false,
            includePolicies: false,
            includeValidation: false,
            includeIndexes: false,
        });

        const userDoc = readDoc(tmpDir, 'models', 'User.md');
        expect(userDoc).not.toContain('## \u{1F517} Relationships');
        expect(userDoc).not.toContain('## \u{1F510} Access Policies');
        expect(userDoc).not.toContain('## \u2705 Validation Rules');
        expect(userDoc).not.toContain('## \u{1F4C7} Indexes');
        expect(fs.existsSync(path.join(tmpDir, 'relationships.md'))).toBe(false);
    });

    it('@@ignore models are excluded by default and included with includeInternalModels=true', async () => {
        const baseSchema = `
            model User {
                id String @id @default(cuid())
            }
            model Internal {
                id String @id @default(cuid())
                @@ignore
            }
        `;

        const excluded = await generateFromSchema(baseSchema);
        const excludedIndex = readDoc(excluded, 'index.md');
        expect(excludedIndex).toContain('[User]');
        expect(excludedIndex).not.toContain('[Internal]');
        expect(fs.existsSync(path.join(excluded, 'models', 'Internal.md'))).toBe(false);

        const included = await generateFromSchema(baseSchema, { includeInternalModels: true });
        const includedIndex = readDoc(included, 'index.md');
        expect(includedIndex).toContain('[Internal]');
        expect(fs.existsSync(path.join(included, 'models', 'Internal.md'))).toBe(true);
    });

    it('links field types to model and enum pages', async () => {
        const tmpDir = await generateFromSchema(`
            model User {
                id    String @id @default(cuid())
                role  Role
                posts Post[]
            }
            model Post {
                id       String @id @default(cuid())
                author   User   @relation(fields: [authorId], references: [id])
                authorId String
            }
            enum Role {
                ADMIN
                USER
            }
        `);

        const userDoc = readDoc(tmpDir, 'models', 'User.md');
        expect(findFieldLine(userDoc, 'role')).toContain('[Role](../enums/Role.md)');
        expect(findFieldLine(userDoc, 'posts')).toContain('[Post](./Post.md)');
        expect(findFieldLine(userDoc, 'id')).not.toContain('[String]');

        const postDoc = readDoc(tmpDir, 'models', 'Post.md');
        expect(findFieldLine(postDoc, 'author')).toContain('[User](./User.md)');
    });

    it('deprecated entities render with strikethrough and badge', async () => {
        const tmpDir = await generateFromSchema(`
            model User {
                id String @id @default(cuid())
                @@meta('doc:deprecated', 'Use Account instead')
            }
            model Account {
                id String @id @default(cuid())
            }
            view OldReport {
                id    String
                total Int
                @@meta('doc:deprecated', 'Use ReportV2 instead')
            }
        `);

        const userDoc = readDoc(tmpDir, 'models', 'User.md');
        expect(userDoc).toContain('# 🗃️ ~~User~~ <kbd>Model</kbd> <kbd>Deprecated</kbd>');

        const indexContent = readDoc(tmpDir, 'index.md');
        expect(indexContent).toContain('~~[User]');
        expect(indexContent).toContain('Use Account instead');
        expect(indexContent).not.toMatch(/~~\[Account\]/);

        const viewDoc = readDoc(tmpDir, 'views', 'OldReport.md');
        expect(viewDoc).toContain('# ~~OldReport~~ <kbd>View</kbd> <kbd>Deprecated</kbd>');
    });

    it('references section links to correct ZenStack documentation URLs', async () => {
        const tmpDir = await generateFromSchema(`
            enum Role { ADMIN USER }
            type Timestamps {
                createdAt DateTime @default(now())
            }
            view UserSummary {
                id Int
            }
            model User with Timestamps {
                id   String @id @default(cuid())
                role Role
            }
        `);

        expect(readDoc(tmpDir, 'models', 'User.md')).toContain('https://zenstack.dev/docs/reference/zmodel/model');
        expect(readDoc(tmpDir, 'enums', 'Role.md')).toContain('https://zenstack.dev/docs/reference/zmodel/enum');
        expect(readDoc(tmpDir, 'types', 'Timestamps.md')).toContain('https://zenstack.dev/docs/reference/zmodel/type');
        expect(readDoc(tmpDir, 'views', 'UserSummary.md')).toContain('https://zenstack.dev/docs/reference/zmodel/view');
    });
});
