//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type Foo = $ModelResult<$Schema, "Foo">;
export type Configuration = $TypeDefResult<$Schema, "Configuration">;
export const ShirtColor = $schema.enums.ShirtColor.values;
export type ShirtColor = (typeof ShirtColor)[keyof typeof ShirtColor];
