//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from './schema';
import type {
    FindManyArgs as $FindManyArgs,
    FindUniqueArgs as $FindUniqueArgs,
    FindFirstArgs as $FindFirstArgs,
    ExistsArgs as $ExistsArgs,
    CreateArgs as $CreateArgs,
    CreateManyArgs as $CreateManyArgs,
    CreateManyAndReturnArgs as $CreateManyAndReturnArgs,
    UpdateArgs as $UpdateArgs,
    UpdateManyArgs as $UpdateManyArgs,
    UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs,
    UpsertArgs as $UpsertArgs,
    DeleteArgs as $DeleteArgs,
    DeleteManyArgs as $DeleteManyArgs,
    CountArgs as $CountArgs,
    AggregateArgs as $AggregateArgs,
    GroupByArgs as $GroupByArgs,
    WhereInput as $WhereInput,
    SelectInput as $SelectInput,
    IncludeInput as $IncludeInput,
    OmitInput as $OmitInput,
    QueryOptions as $QueryOptions,
} from '@zenstackhq/orm';
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from '@zenstackhq/orm';
export type UserFindManyArgs = $FindManyArgs<$Schema, 'User'>;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, 'User'>;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, 'User'>;
export type UserExistsArgs = $ExistsArgs<$Schema, 'User'>;
export type UserCreateArgs = $CreateArgs<$Schema, 'User'>;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, 'User'>;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpdateArgs = $UpdateArgs<$Schema, 'User'>;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, 'User'>;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpsertArgs = $UpsertArgs<$Schema, 'User'>;
export type UserDeleteArgs = $DeleteArgs<$Schema, 'User'>;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, 'User'>;
export type UserCountArgs = $CountArgs<$Schema, 'User'>;
export type UserAggregateArgs = $AggregateArgs<$Schema, 'User'>;
export type UserGroupByArgs = $GroupByArgs<$Schema, 'User'>;
export type UserWhereInput = $WhereInput<$Schema, 'User'>;
export type UserSelect = $SelectInput<$Schema, 'User'>;
export type UserInclude = $IncludeInput<$Schema, 'User'>;
export type UserOmit = $OmitInput<$Schema, 'User'>;
export type UserGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'User', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'User', Args, Options>;
export type PostFindManyArgs = $FindManyArgs<$Schema, 'Post'>;
export type PostFindUniqueArgs = $FindUniqueArgs<$Schema, 'Post'>;
export type PostFindFirstArgs = $FindFirstArgs<$Schema, 'Post'>;
export type PostExistsArgs = $ExistsArgs<$Schema, 'Post'>;
export type PostCreateArgs = $CreateArgs<$Schema, 'Post'>;
export type PostCreateManyArgs = $CreateManyArgs<$Schema, 'Post'>;
export type PostCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Post'>;
export type PostUpdateArgs = $UpdateArgs<$Schema, 'Post'>;
export type PostUpdateManyArgs = $UpdateManyArgs<$Schema, 'Post'>;
export type PostUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Post'>;
export type PostUpsertArgs = $UpsertArgs<$Schema, 'Post'>;
export type PostDeleteArgs = $DeleteArgs<$Schema, 'Post'>;
export type PostDeleteManyArgs = $DeleteManyArgs<$Schema, 'Post'>;
export type PostCountArgs = $CountArgs<$Schema, 'Post'>;
export type PostAggregateArgs = $AggregateArgs<$Schema, 'Post'>;
export type PostGroupByArgs = $GroupByArgs<$Schema, 'Post'>;
export type PostWhereInput = $WhereInput<$Schema, 'Post'>;
export type PostSelect = $SelectInput<$Schema, 'Post'>;
export type PostInclude = $IncludeInput<$Schema, 'Post'>;
export type PostOmit = $OmitInput<$Schema, 'Post'>;
export type PostGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Post', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Post', Args, Options>;
export type ProfileFindManyArgs = $FindManyArgs<$Schema, 'Profile'>;
export type ProfileFindUniqueArgs = $FindUniqueArgs<$Schema, 'Profile'>;
export type ProfileFindFirstArgs = $FindFirstArgs<$Schema, 'Profile'>;
export type ProfileExistsArgs = $ExistsArgs<$Schema, 'Profile'>;
export type ProfileCreateArgs = $CreateArgs<$Schema, 'Profile'>;
export type ProfileCreateManyArgs = $CreateManyArgs<$Schema, 'Profile'>;
export type ProfileCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Profile'>;
export type ProfileUpdateArgs = $UpdateArgs<$Schema, 'Profile'>;
export type ProfileUpdateManyArgs = $UpdateManyArgs<$Schema, 'Profile'>;
export type ProfileUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Profile'>;
export type ProfileUpsertArgs = $UpsertArgs<$Schema, 'Profile'>;
export type ProfileDeleteArgs = $DeleteArgs<$Schema, 'Profile'>;
export type ProfileDeleteManyArgs = $DeleteManyArgs<$Schema, 'Profile'>;
export type ProfileCountArgs = $CountArgs<$Schema, 'Profile'>;
export type ProfileAggregateArgs = $AggregateArgs<$Schema, 'Profile'>;
export type ProfileGroupByArgs = $GroupByArgs<$Schema, 'Profile'>;
export type ProfileWhereInput = $WhereInput<$Schema, 'Profile'>;
export type ProfileSelect = $SelectInput<$Schema, 'Profile'>;
export type ProfileInclude = $IncludeInput<$Schema, 'Profile'>;
export type ProfileOmit = $OmitInput<$Schema, 'Profile'>;
export type ProfileGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Profile', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Profile', Args, Options>;
export type TagFindManyArgs = $FindManyArgs<$Schema, 'Tag'>;
export type TagFindUniqueArgs = $FindUniqueArgs<$Schema, 'Tag'>;
export type TagFindFirstArgs = $FindFirstArgs<$Schema, 'Tag'>;
export type TagExistsArgs = $ExistsArgs<$Schema, 'Tag'>;
export type TagCreateArgs = $CreateArgs<$Schema, 'Tag'>;
export type TagCreateManyArgs = $CreateManyArgs<$Schema, 'Tag'>;
export type TagCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Tag'>;
export type TagUpdateArgs = $UpdateArgs<$Schema, 'Tag'>;
export type TagUpdateManyArgs = $UpdateManyArgs<$Schema, 'Tag'>;
export type TagUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Tag'>;
export type TagUpsertArgs = $UpsertArgs<$Schema, 'Tag'>;
export type TagDeleteArgs = $DeleteArgs<$Schema, 'Tag'>;
export type TagDeleteManyArgs = $DeleteManyArgs<$Schema, 'Tag'>;
export type TagCountArgs = $CountArgs<$Schema, 'Tag'>;
export type TagAggregateArgs = $AggregateArgs<$Schema, 'Tag'>;
export type TagGroupByArgs = $GroupByArgs<$Schema, 'Tag'>;
export type TagWhereInput = $WhereInput<$Schema, 'Tag'>;
export type TagSelect = $SelectInput<$Schema, 'Tag'>;
export type TagInclude = $IncludeInput<$Schema, 'Tag'>;
export type TagOmit = $OmitInput<$Schema, 'Tag'>;
export type TagGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Tag', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Tag', Args, Options>;
export type RegionFindManyArgs = $FindManyArgs<$Schema, 'Region'>;
export type RegionFindUniqueArgs = $FindUniqueArgs<$Schema, 'Region'>;
export type RegionFindFirstArgs = $FindFirstArgs<$Schema, 'Region'>;
export type RegionExistsArgs = $ExistsArgs<$Schema, 'Region'>;
export type RegionCreateArgs = $CreateArgs<$Schema, 'Region'>;
export type RegionCreateManyArgs = $CreateManyArgs<$Schema, 'Region'>;
export type RegionCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Region'>;
export type RegionUpdateArgs = $UpdateArgs<$Schema, 'Region'>;
export type RegionUpdateManyArgs = $UpdateManyArgs<$Schema, 'Region'>;
export type RegionUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Region'>;
export type RegionUpsertArgs = $UpsertArgs<$Schema, 'Region'>;
export type RegionDeleteArgs = $DeleteArgs<$Schema, 'Region'>;
export type RegionDeleteManyArgs = $DeleteManyArgs<$Schema, 'Region'>;
export type RegionCountArgs = $CountArgs<$Schema, 'Region'>;
export type RegionAggregateArgs = $AggregateArgs<$Schema, 'Region'>;
export type RegionGroupByArgs = $GroupByArgs<$Schema, 'Region'>;
export type RegionWhereInput = $WhereInput<$Schema, 'Region'>;
export type RegionSelect = $SelectInput<$Schema, 'Region'>;
export type RegionInclude = $IncludeInput<$Schema, 'Region'>;
export type RegionOmit = $OmitInput<$Schema, 'Region'>;
export type RegionGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Region', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Region', Args, Options>;
export type MetaFindManyArgs = $FindManyArgs<$Schema, 'Meta'>;
export type MetaFindUniqueArgs = $FindUniqueArgs<$Schema, 'Meta'>;
export type MetaFindFirstArgs = $FindFirstArgs<$Schema, 'Meta'>;
export type MetaExistsArgs = $ExistsArgs<$Schema, 'Meta'>;
export type MetaCreateArgs = $CreateArgs<$Schema, 'Meta'>;
export type MetaCreateManyArgs = $CreateManyArgs<$Schema, 'Meta'>;
export type MetaCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Meta'>;
export type MetaUpdateArgs = $UpdateArgs<$Schema, 'Meta'>;
export type MetaUpdateManyArgs = $UpdateManyArgs<$Schema, 'Meta'>;
export type MetaUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Meta'>;
export type MetaUpsertArgs = $UpsertArgs<$Schema, 'Meta'>;
export type MetaDeleteArgs = $DeleteArgs<$Schema, 'Meta'>;
export type MetaDeleteManyArgs = $DeleteManyArgs<$Schema, 'Meta'>;
export type MetaCountArgs = $CountArgs<$Schema, 'Meta'>;
export type MetaAggregateArgs = $AggregateArgs<$Schema, 'Meta'>;
export type MetaGroupByArgs = $GroupByArgs<$Schema, 'Meta'>;
export type MetaWhereInput = $WhereInput<$Schema, 'Meta'>;
export type MetaSelect = $SelectInput<$Schema, 'Meta'>;
export type MetaInclude = $IncludeInput<$Schema, 'Meta'>;
export type MetaOmit = $OmitInput<$Schema, 'Meta'>;
export type MetaGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Meta', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Meta', Args, Options>;
