//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from './schema';
import type {
    FindManyArgs as $FindManyArgs,
    FindUniqueArgs as $FindUniqueArgs,
    FindFirstArgs as $FindFirstArgs,
    ExistsArgs as $ExistsArgs,
    CreateArgs as $CreateArgs,
    CreateManyArgs as $CreateManyArgs,
    CreateManyAndReturnArgs as $CreateManyAndReturnArgs,
    UpdateArgs as $UpdateArgs,
    UpdateManyArgs as $UpdateManyArgs,
    UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs,
    UpsertArgs as $UpsertArgs,
    DeleteArgs as $DeleteArgs,
    DeleteManyArgs as $DeleteManyArgs,
    CountArgs as $CountArgs,
    AggregateArgs as $AggregateArgs,
    GroupByArgs as $GroupByArgs,
    WhereInput as $WhereInput,
    SelectInput as $SelectInput,
    IncludeInput as $IncludeInput,
    OmitInput as $OmitInput,
    QueryOptions as $QueryOptions,
} from '@zenstackhq/orm';
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from '@zenstackhq/orm';
export type WebhookFindManyArgs = $FindManyArgs<$Schema, 'Webhook'>;
export type WebhookFindUniqueArgs = $FindUniqueArgs<$Schema, 'Webhook'>;
export type WebhookFindFirstArgs = $FindFirstArgs<$Schema, 'Webhook'>;
export type WebhookExistsArgs = $ExistsArgs<$Schema, 'Webhook'>;
export type WebhookCreateArgs = $CreateArgs<$Schema, 'Webhook'>;
export type WebhookCreateManyArgs = $CreateManyArgs<$Schema, 'Webhook'>;
export type WebhookCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Webhook'>;
export type WebhookUpdateArgs = $UpdateArgs<$Schema, 'Webhook'>;
export type WebhookUpdateManyArgs = $UpdateManyArgs<$Schema, 'Webhook'>;
export type WebhookUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Webhook'>;
export type WebhookUpsertArgs = $UpsertArgs<$Schema, 'Webhook'>;
export type WebhookDeleteArgs = $DeleteArgs<$Schema, 'Webhook'>;
export type WebhookDeleteManyArgs = $DeleteManyArgs<$Schema, 'Webhook'>;
export type WebhookCountArgs = $CountArgs<$Schema, 'Webhook'>;
export type WebhookAggregateArgs = $AggregateArgs<$Schema, 'Webhook'>;
export type WebhookGroupByArgs = $GroupByArgs<$Schema, 'Webhook'>;
export type WebhookWhereInput = $WhereInput<$Schema, 'Webhook'>;
export type WebhookSelect = $SelectInput<$Schema, 'Webhook'>;
export type WebhookInclude = $IncludeInput<$Schema, 'Webhook'>;
export type WebhookOmit = $OmitInput<$Schema, 'Webhook'>;
export type WebhookGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Webhook', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Webhook', Args, Options>;
export type ContactAttributeFindManyArgs = $FindManyArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeFindUniqueArgs = $FindUniqueArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeFindFirstArgs = $FindFirstArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeExistsArgs = $ExistsArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeCreateArgs = $CreateArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeCreateManyArgs = $CreateManyArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeUpdateArgs = $UpdateArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeUpdateManyArgs = $UpdateManyArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeUpsertArgs = $UpsertArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeDeleteArgs = $DeleteArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeDeleteManyArgs = $DeleteManyArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeCountArgs = $CountArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeAggregateArgs = $AggregateArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeGroupByArgs = $GroupByArgs<$Schema, 'ContactAttribute'>;
export type ContactAttributeWhereInput = $WhereInput<$Schema, 'ContactAttribute'>;
export type ContactAttributeSelect = $SelectInput<$Schema, 'ContactAttribute'>;
export type ContactAttributeInclude = $IncludeInput<$Schema, 'ContactAttribute'>;
export type ContactAttributeOmit = $OmitInput<$Schema, 'ContactAttribute'>;
export type ContactAttributeGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ContactAttribute', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ContactAttribute', Args, Options>;
export type ContactAttributeKeyFindManyArgs = $FindManyArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyFindUniqueArgs = $FindUniqueArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyFindFirstArgs = $FindFirstArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyExistsArgs = $ExistsArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyCreateArgs = $CreateArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyCreateManyArgs = $CreateManyArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyUpdateArgs = $UpdateArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyUpdateManyArgs = $UpdateManyArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyUpsertArgs = $UpsertArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyDeleteArgs = $DeleteArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyDeleteManyArgs = $DeleteManyArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyCountArgs = $CountArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyAggregateArgs = $AggregateArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyGroupByArgs = $GroupByArgs<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyWhereInput = $WhereInput<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeySelect = $SelectInput<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyInclude = $IncludeInput<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyOmit = $OmitInput<$Schema, 'ContactAttributeKey'>;
export type ContactAttributeKeyGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ContactAttributeKey', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ContactAttributeKey', Args, Options>;
export type ContactFindManyArgs = $FindManyArgs<$Schema, 'Contact'>;
export type ContactFindUniqueArgs = $FindUniqueArgs<$Schema, 'Contact'>;
export type ContactFindFirstArgs = $FindFirstArgs<$Schema, 'Contact'>;
export type ContactExistsArgs = $ExistsArgs<$Schema, 'Contact'>;
export type ContactCreateArgs = $CreateArgs<$Schema, 'Contact'>;
export type ContactCreateManyArgs = $CreateManyArgs<$Schema, 'Contact'>;
export type ContactCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Contact'>;
export type ContactUpdateArgs = $UpdateArgs<$Schema, 'Contact'>;
export type ContactUpdateManyArgs = $UpdateManyArgs<$Schema, 'Contact'>;
export type ContactUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Contact'>;
export type ContactUpsertArgs = $UpsertArgs<$Schema, 'Contact'>;
export type ContactDeleteArgs = $DeleteArgs<$Schema, 'Contact'>;
export type ContactDeleteManyArgs = $DeleteManyArgs<$Schema, 'Contact'>;
export type ContactCountArgs = $CountArgs<$Schema, 'Contact'>;
export type ContactAggregateArgs = $AggregateArgs<$Schema, 'Contact'>;
export type ContactGroupByArgs = $GroupByArgs<$Schema, 'Contact'>;
export type ContactWhereInput = $WhereInput<$Schema, 'Contact'>;
export type ContactSelect = $SelectInput<$Schema, 'Contact'>;
export type ContactInclude = $IncludeInput<$Schema, 'Contact'>;
export type ContactOmit = $OmitInput<$Schema, 'Contact'>;
export type ContactGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Contact', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Contact', Args, Options>;
export type ResponseFindManyArgs = $FindManyArgs<$Schema, 'Response'>;
export type ResponseFindUniqueArgs = $FindUniqueArgs<$Schema, 'Response'>;
export type ResponseFindFirstArgs = $FindFirstArgs<$Schema, 'Response'>;
export type ResponseExistsArgs = $ExistsArgs<$Schema, 'Response'>;
export type ResponseCreateArgs = $CreateArgs<$Schema, 'Response'>;
export type ResponseCreateManyArgs = $CreateManyArgs<$Schema, 'Response'>;
export type ResponseCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Response'>;
export type ResponseUpdateArgs = $UpdateArgs<$Schema, 'Response'>;
export type ResponseUpdateManyArgs = $UpdateManyArgs<$Schema, 'Response'>;
export type ResponseUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Response'>;
export type ResponseUpsertArgs = $UpsertArgs<$Schema, 'Response'>;
export type ResponseDeleteArgs = $DeleteArgs<$Schema, 'Response'>;
export type ResponseDeleteManyArgs = $DeleteManyArgs<$Schema, 'Response'>;
export type ResponseCountArgs = $CountArgs<$Schema, 'Response'>;
export type ResponseAggregateArgs = $AggregateArgs<$Schema, 'Response'>;
export type ResponseGroupByArgs = $GroupByArgs<$Schema, 'Response'>;
export type ResponseWhereInput = $WhereInput<$Schema, 'Response'>;
export type ResponseSelect = $SelectInput<$Schema, 'Response'>;
export type ResponseInclude = $IncludeInput<$Schema, 'Response'>;
export type ResponseOmit = $OmitInput<$Schema, 'Response'>;
export type ResponseGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Response', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Response', Args, Options>;
export type ResponseNoteFindManyArgs = $FindManyArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteFindUniqueArgs = $FindUniqueArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteFindFirstArgs = $FindFirstArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteExistsArgs = $ExistsArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteCreateArgs = $CreateArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteCreateManyArgs = $CreateManyArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteUpdateArgs = $UpdateArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteUpdateManyArgs = $UpdateManyArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteUpsertArgs = $UpsertArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteDeleteArgs = $DeleteArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteDeleteManyArgs = $DeleteManyArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteCountArgs = $CountArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteAggregateArgs = $AggregateArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteGroupByArgs = $GroupByArgs<$Schema, 'ResponseNote'>;
export type ResponseNoteWhereInput = $WhereInput<$Schema, 'ResponseNote'>;
export type ResponseNoteSelect = $SelectInput<$Schema, 'ResponseNote'>;
export type ResponseNoteInclude = $IncludeInput<$Schema, 'ResponseNote'>;
export type ResponseNoteOmit = $OmitInput<$Schema, 'ResponseNote'>;
export type ResponseNoteGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ResponseNote', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ResponseNote', Args, Options>;
export type TagFindManyArgs = $FindManyArgs<$Schema, 'Tag'>;
export type TagFindUniqueArgs = $FindUniqueArgs<$Schema, 'Tag'>;
export type TagFindFirstArgs = $FindFirstArgs<$Schema, 'Tag'>;
export type TagExistsArgs = $ExistsArgs<$Schema, 'Tag'>;
export type TagCreateArgs = $CreateArgs<$Schema, 'Tag'>;
export type TagCreateManyArgs = $CreateManyArgs<$Schema, 'Tag'>;
export type TagCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Tag'>;
export type TagUpdateArgs = $UpdateArgs<$Schema, 'Tag'>;
export type TagUpdateManyArgs = $UpdateManyArgs<$Schema, 'Tag'>;
export type TagUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Tag'>;
export type TagUpsertArgs = $UpsertArgs<$Schema, 'Tag'>;
export type TagDeleteArgs = $DeleteArgs<$Schema, 'Tag'>;
export type TagDeleteManyArgs = $DeleteManyArgs<$Schema, 'Tag'>;
export type TagCountArgs = $CountArgs<$Schema, 'Tag'>;
export type TagAggregateArgs = $AggregateArgs<$Schema, 'Tag'>;
export type TagGroupByArgs = $GroupByArgs<$Schema, 'Tag'>;
export type TagWhereInput = $WhereInput<$Schema, 'Tag'>;
export type TagSelect = $SelectInput<$Schema, 'Tag'>;
export type TagInclude = $IncludeInput<$Schema, 'Tag'>;
export type TagOmit = $OmitInput<$Schema, 'Tag'>;
export type TagGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Tag', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Tag', Args, Options>;
export type TagsOnResponsesFindManyArgs = $FindManyArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesFindUniqueArgs = $FindUniqueArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesFindFirstArgs = $FindFirstArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesExistsArgs = $ExistsArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesCreateArgs = $CreateArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesCreateManyArgs = $CreateManyArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesUpdateArgs = $UpdateArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesUpdateManyArgs = $UpdateManyArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesUpsertArgs = $UpsertArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesDeleteArgs = $DeleteArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesDeleteManyArgs = $DeleteManyArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesCountArgs = $CountArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesAggregateArgs = $AggregateArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesGroupByArgs = $GroupByArgs<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesWhereInput = $WhereInput<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesSelect = $SelectInput<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesInclude = $IncludeInput<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesOmit = $OmitInput<$Schema, 'TagsOnResponses'>;
export type TagsOnResponsesGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'TagsOnResponses', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'TagsOnResponses', Args, Options>;
export type DisplayFindManyArgs = $FindManyArgs<$Schema, 'Display'>;
export type DisplayFindUniqueArgs = $FindUniqueArgs<$Schema, 'Display'>;
export type DisplayFindFirstArgs = $FindFirstArgs<$Schema, 'Display'>;
export type DisplayExistsArgs = $ExistsArgs<$Schema, 'Display'>;
export type DisplayCreateArgs = $CreateArgs<$Schema, 'Display'>;
export type DisplayCreateManyArgs = $CreateManyArgs<$Schema, 'Display'>;
export type DisplayCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Display'>;
export type DisplayUpdateArgs = $UpdateArgs<$Schema, 'Display'>;
export type DisplayUpdateManyArgs = $UpdateManyArgs<$Schema, 'Display'>;
export type DisplayUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Display'>;
export type DisplayUpsertArgs = $UpsertArgs<$Schema, 'Display'>;
export type DisplayDeleteArgs = $DeleteArgs<$Schema, 'Display'>;
export type DisplayDeleteManyArgs = $DeleteManyArgs<$Schema, 'Display'>;
export type DisplayCountArgs = $CountArgs<$Schema, 'Display'>;
export type DisplayAggregateArgs = $AggregateArgs<$Schema, 'Display'>;
export type DisplayGroupByArgs = $GroupByArgs<$Schema, 'Display'>;
export type DisplayWhereInput = $WhereInput<$Schema, 'Display'>;
export type DisplaySelect = $SelectInput<$Schema, 'Display'>;
export type DisplayInclude = $IncludeInput<$Schema, 'Display'>;
export type DisplayOmit = $OmitInput<$Schema, 'Display'>;
export type DisplayGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Display', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Display', Args, Options>;
export type SurveyTriggerFindManyArgs = $FindManyArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerFindUniqueArgs = $FindUniqueArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerFindFirstArgs = $FindFirstArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerExistsArgs = $ExistsArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerCreateArgs = $CreateArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerCreateManyArgs = $CreateManyArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerUpdateArgs = $UpdateArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerUpdateManyArgs = $UpdateManyArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerUpsertArgs = $UpsertArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerDeleteArgs = $DeleteArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerDeleteManyArgs = $DeleteManyArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerCountArgs = $CountArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerAggregateArgs = $AggregateArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerGroupByArgs = $GroupByArgs<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerWhereInput = $WhereInput<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerSelect = $SelectInput<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerInclude = $IncludeInput<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerOmit = $OmitInput<$Schema, 'SurveyTrigger'>;
export type SurveyTriggerGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'SurveyTrigger', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SurveyTrigger', Args, Options>;
export type SurveyAttributeFilterFindManyArgs = $FindManyArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterFindUniqueArgs = $FindUniqueArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterFindFirstArgs = $FindFirstArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterExistsArgs = $ExistsArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterCreateArgs = $CreateArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterCreateManyArgs = $CreateManyArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterUpdateArgs = $UpdateArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterUpdateManyArgs = $UpdateManyArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterUpsertArgs = $UpsertArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterDeleteArgs = $DeleteArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterDeleteManyArgs = $DeleteManyArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterCountArgs = $CountArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterAggregateArgs = $AggregateArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterGroupByArgs = $GroupByArgs<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterWhereInput = $WhereInput<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterSelect = $SelectInput<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterInclude = $IncludeInput<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterOmit = $OmitInput<$Schema, 'SurveyAttributeFilter'>;
export type SurveyAttributeFilterGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'SurveyAttributeFilter', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SurveyAttributeFilter', Args, Options>;
export type SurveyFindManyArgs = $FindManyArgs<$Schema, 'Survey'>;
export type SurveyFindUniqueArgs = $FindUniqueArgs<$Schema, 'Survey'>;
export type SurveyFindFirstArgs = $FindFirstArgs<$Schema, 'Survey'>;
export type SurveyExistsArgs = $ExistsArgs<$Schema, 'Survey'>;
export type SurveyCreateArgs = $CreateArgs<$Schema, 'Survey'>;
export type SurveyCreateManyArgs = $CreateManyArgs<$Schema, 'Survey'>;
export type SurveyCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Survey'>;
export type SurveyUpdateArgs = $UpdateArgs<$Schema, 'Survey'>;
export type SurveyUpdateManyArgs = $UpdateManyArgs<$Schema, 'Survey'>;
export type SurveyUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Survey'>;
export type SurveyUpsertArgs = $UpsertArgs<$Schema, 'Survey'>;
export type SurveyDeleteArgs = $DeleteArgs<$Schema, 'Survey'>;
export type SurveyDeleteManyArgs = $DeleteManyArgs<$Schema, 'Survey'>;
export type SurveyCountArgs = $CountArgs<$Schema, 'Survey'>;
export type SurveyAggregateArgs = $AggregateArgs<$Schema, 'Survey'>;
export type SurveyGroupByArgs = $GroupByArgs<$Schema, 'Survey'>;
export type SurveyWhereInput = $WhereInput<$Schema, 'Survey'>;
export type SurveySelect = $SelectInput<$Schema, 'Survey'>;
export type SurveyInclude = $IncludeInput<$Schema, 'Survey'>;
export type SurveyOmit = $OmitInput<$Schema, 'Survey'>;
export type SurveyGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Survey', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Survey', Args, Options>;
export type SurveyFollowUpFindManyArgs = $FindManyArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpFindUniqueArgs = $FindUniqueArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpFindFirstArgs = $FindFirstArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpExistsArgs = $ExistsArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpCreateArgs = $CreateArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpCreateManyArgs = $CreateManyArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpUpdateArgs = $UpdateArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpUpdateManyArgs = $UpdateManyArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpUpsertArgs = $UpsertArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpDeleteArgs = $DeleteArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpDeleteManyArgs = $DeleteManyArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpCountArgs = $CountArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpAggregateArgs = $AggregateArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpGroupByArgs = $GroupByArgs<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpWhereInput = $WhereInput<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpSelect = $SelectInput<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpInclude = $IncludeInput<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpOmit = $OmitInput<$Schema, 'SurveyFollowUp'>;
export type SurveyFollowUpGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'SurveyFollowUp', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SurveyFollowUp', Args, Options>;
export type ActionClassFindManyArgs = $FindManyArgs<$Schema, 'ActionClass'>;
export type ActionClassFindUniqueArgs = $FindUniqueArgs<$Schema, 'ActionClass'>;
export type ActionClassFindFirstArgs = $FindFirstArgs<$Schema, 'ActionClass'>;
export type ActionClassExistsArgs = $ExistsArgs<$Schema, 'ActionClass'>;
export type ActionClassCreateArgs = $CreateArgs<$Schema, 'ActionClass'>;
export type ActionClassCreateManyArgs = $CreateManyArgs<$Schema, 'ActionClass'>;
export type ActionClassCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ActionClass'>;
export type ActionClassUpdateArgs = $UpdateArgs<$Schema, 'ActionClass'>;
export type ActionClassUpdateManyArgs = $UpdateManyArgs<$Schema, 'ActionClass'>;
export type ActionClassUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ActionClass'>;
export type ActionClassUpsertArgs = $UpsertArgs<$Schema, 'ActionClass'>;
export type ActionClassDeleteArgs = $DeleteArgs<$Schema, 'ActionClass'>;
export type ActionClassDeleteManyArgs = $DeleteManyArgs<$Schema, 'ActionClass'>;
export type ActionClassCountArgs = $CountArgs<$Schema, 'ActionClass'>;
export type ActionClassAggregateArgs = $AggregateArgs<$Schema, 'ActionClass'>;
export type ActionClassGroupByArgs = $GroupByArgs<$Schema, 'ActionClass'>;
export type ActionClassWhereInput = $WhereInput<$Schema, 'ActionClass'>;
export type ActionClassSelect = $SelectInput<$Schema, 'ActionClass'>;
export type ActionClassInclude = $IncludeInput<$Schema, 'ActionClass'>;
export type ActionClassOmit = $OmitInput<$Schema, 'ActionClass'>;
export type ActionClassGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ActionClass', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ActionClass', Args, Options>;
export type IntegrationFindManyArgs = $FindManyArgs<$Schema, 'Integration'>;
export type IntegrationFindUniqueArgs = $FindUniqueArgs<$Schema, 'Integration'>;
export type IntegrationFindFirstArgs = $FindFirstArgs<$Schema, 'Integration'>;
export type IntegrationExistsArgs = $ExistsArgs<$Schema, 'Integration'>;
export type IntegrationCreateArgs = $CreateArgs<$Schema, 'Integration'>;
export type IntegrationCreateManyArgs = $CreateManyArgs<$Schema, 'Integration'>;
export type IntegrationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Integration'>;
export type IntegrationUpdateArgs = $UpdateArgs<$Schema, 'Integration'>;
export type IntegrationUpdateManyArgs = $UpdateManyArgs<$Schema, 'Integration'>;
export type IntegrationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Integration'>;
export type IntegrationUpsertArgs = $UpsertArgs<$Schema, 'Integration'>;
export type IntegrationDeleteArgs = $DeleteArgs<$Schema, 'Integration'>;
export type IntegrationDeleteManyArgs = $DeleteManyArgs<$Schema, 'Integration'>;
export type IntegrationCountArgs = $CountArgs<$Schema, 'Integration'>;
export type IntegrationAggregateArgs = $AggregateArgs<$Schema, 'Integration'>;
export type IntegrationGroupByArgs = $GroupByArgs<$Schema, 'Integration'>;
export type IntegrationWhereInput = $WhereInput<$Schema, 'Integration'>;
export type IntegrationSelect = $SelectInput<$Schema, 'Integration'>;
export type IntegrationInclude = $IncludeInput<$Schema, 'Integration'>;
export type IntegrationOmit = $OmitInput<$Schema, 'Integration'>;
export type IntegrationGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Integration', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Integration', Args, Options>;
export type DataMigrationFindManyArgs = $FindManyArgs<$Schema, 'DataMigration'>;
export type DataMigrationFindUniqueArgs = $FindUniqueArgs<$Schema, 'DataMigration'>;
export type DataMigrationFindFirstArgs = $FindFirstArgs<$Schema, 'DataMigration'>;
export type DataMigrationExistsArgs = $ExistsArgs<$Schema, 'DataMigration'>;
export type DataMigrationCreateArgs = $CreateArgs<$Schema, 'DataMigration'>;
export type DataMigrationCreateManyArgs = $CreateManyArgs<$Schema, 'DataMigration'>;
export type DataMigrationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'DataMigration'>;
export type DataMigrationUpdateArgs = $UpdateArgs<$Schema, 'DataMigration'>;
export type DataMigrationUpdateManyArgs = $UpdateManyArgs<$Schema, 'DataMigration'>;
export type DataMigrationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'DataMigration'>;
export type DataMigrationUpsertArgs = $UpsertArgs<$Schema, 'DataMigration'>;
export type DataMigrationDeleteArgs = $DeleteArgs<$Schema, 'DataMigration'>;
export type DataMigrationDeleteManyArgs = $DeleteManyArgs<$Schema, 'DataMigration'>;
export type DataMigrationCountArgs = $CountArgs<$Schema, 'DataMigration'>;
export type DataMigrationAggregateArgs = $AggregateArgs<$Schema, 'DataMigration'>;
export type DataMigrationGroupByArgs = $GroupByArgs<$Schema, 'DataMigration'>;
export type DataMigrationWhereInput = $WhereInput<$Schema, 'DataMigration'>;
export type DataMigrationSelect = $SelectInput<$Schema, 'DataMigration'>;
export type DataMigrationInclude = $IncludeInput<$Schema, 'DataMigration'>;
export type DataMigrationOmit = $OmitInput<$Schema, 'DataMigration'>;
export type DataMigrationGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'DataMigration', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'DataMigration', Args, Options>;
export type EnvironmentFindManyArgs = $FindManyArgs<$Schema, 'Environment'>;
export type EnvironmentFindUniqueArgs = $FindUniqueArgs<$Schema, 'Environment'>;
export type EnvironmentFindFirstArgs = $FindFirstArgs<$Schema, 'Environment'>;
export type EnvironmentExistsArgs = $ExistsArgs<$Schema, 'Environment'>;
export type EnvironmentCreateArgs = $CreateArgs<$Schema, 'Environment'>;
export type EnvironmentCreateManyArgs = $CreateManyArgs<$Schema, 'Environment'>;
export type EnvironmentCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Environment'>;
export type EnvironmentUpdateArgs = $UpdateArgs<$Schema, 'Environment'>;
export type EnvironmentUpdateManyArgs = $UpdateManyArgs<$Schema, 'Environment'>;
export type EnvironmentUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Environment'>;
export type EnvironmentUpsertArgs = $UpsertArgs<$Schema, 'Environment'>;
export type EnvironmentDeleteArgs = $DeleteArgs<$Schema, 'Environment'>;
export type EnvironmentDeleteManyArgs = $DeleteManyArgs<$Schema, 'Environment'>;
export type EnvironmentCountArgs = $CountArgs<$Schema, 'Environment'>;
export type EnvironmentAggregateArgs = $AggregateArgs<$Schema, 'Environment'>;
export type EnvironmentGroupByArgs = $GroupByArgs<$Schema, 'Environment'>;
export type EnvironmentWhereInput = $WhereInput<$Schema, 'Environment'>;
export type EnvironmentSelect = $SelectInput<$Schema, 'Environment'>;
export type EnvironmentInclude = $IncludeInput<$Schema, 'Environment'>;
export type EnvironmentOmit = $OmitInput<$Schema, 'Environment'>;
export type EnvironmentGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Environment', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Environment', Args, Options>;
export type ProjectFindManyArgs = $FindManyArgs<$Schema, 'Project'>;
export type ProjectFindUniqueArgs = $FindUniqueArgs<$Schema, 'Project'>;
export type ProjectFindFirstArgs = $FindFirstArgs<$Schema, 'Project'>;
export type ProjectExistsArgs = $ExistsArgs<$Schema, 'Project'>;
export type ProjectCreateArgs = $CreateArgs<$Schema, 'Project'>;
export type ProjectCreateManyArgs = $CreateManyArgs<$Schema, 'Project'>;
export type ProjectCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Project'>;
export type ProjectUpdateArgs = $UpdateArgs<$Schema, 'Project'>;
export type ProjectUpdateManyArgs = $UpdateManyArgs<$Schema, 'Project'>;
export type ProjectUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Project'>;
export type ProjectUpsertArgs = $UpsertArgs<$Schema, 'Project'>;
export type ProjectDeleteArgs = $DeleteArgs<$Schema, 'Project'>;
export type ProjectDeleteManyArgs = $DeleteManyArgs<$Schema, 'Project'>;
export type ProjectCountArgs = $CountArgs<$Schema, 'Project'>;
export type ProjectAggregateArgs = $AggregateArgs<$Schema, 'Project'>;
export type ProjectGroupByArgs = $GroupByArgs<$Schema, 'Project'>;
export type ProjectWhereInput = $WhereInput<$Schema, 'Project'>;
export type ProjectSelect = $SelectInput<$Schema, 'Project'>;
export type ProjectInclude = $IncludeInput<$Schema, 'Project'>;
export type ProjectOmit = $OmitInput<$Schema, 'Project'>;
export type ProjectGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Project', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Project', Args, Options>;
export type OrganizationFindManyArgs = $FindManyArgs<$Schema, 'Organization'>;
export type OrganizationFindUniqueArgs = $FindUniqueArgs<$Schema, 'Organization'>;
export type OrganizationFindFirstArgs = $FindFirstArgs<$Schema, 'Organization'>;
export type OrganizationExistsArgs = $ExistsArgs<$Schema, 'Organization'>;
export type OrganizationCreateArgs = $CreateArgs<$Schema, 'Organization'>;
export type OrganizationCreateManyArgs = $CreateManyArgs<$Schema, 'Organization'>;
export type OrganizationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Organization'>;
export type OrganizationUpdateArgs = $UpdateArgs<$Schema, 'Organization'>;
export type OrganizationUpdateManyArgs = $UpdateManyArgs<$Schema, 'Organization'>;
export type OrganizationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Organization'>;
export type OrganizationUpsertArgs = $UpsertArgs<$Schema, 'Organization'>;
export type OrganizationDeleteArgs = $DeleteArgs<$Schema, 'Organization'>;
export type OrganizationDeleteManyArgs = $DeleteManyArgs<$Schema, 'Organization'>;
export type OrganizationCountArgs = $CountArgs<$Schema, 'Organization'>;
export type OrganizationAggregateArgs = $AggregateArgs<$Schema, 'Organization'>;
export type OrganizationGroupByArgs = $GroupByArgs<$Schema, 'Organization'>;
export type OrganizationWhereInput = $WhereInput<$Schema, 'Organization'>;
export type OrganizationSelect = $SelectInput<$Schema, 'Organization'>;
export type OrganizationInclude = $IncludeInput<$Schema, 'Organization'>;
export type OrganizationOmit = $OmitInput<$Schema, 'Organization'>;
export type OrganizationGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Organization', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Organization', Args, Options>;
export type MembershipFindManyArgs = $FindManyArgs<$Schema, 'Membership'>;
export type MembershipFindUniqueArgs = $FindUniqueArgs<$Schema, 'Membership'>;
export type MembershipFindFirstArgs = $FindFirstArgs<$Schema, 'Membership'>;
export type MembershipExistsArgs = $ExistsArgs<$Schema, 'Membership'>;
export type MembershipCreateArgs = $CreateArgs<$Schema, 'Membership'>;
export type MembershipCreateManyArgs = $CreateManyArgs<$Schema, 'Membership'>;
export type MembershipCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Membership'>;
export type MembershipUpdateArgs = $UpdateArgs<$Schema, 'Membership'>;
export type MembershipUpdateManyArgs = $UpdateManyArgs<$Schema, 'Membership'>;
export type MembershipUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Membership'>;
export type MembershipUpsertArgs = $UpsertArgs<$Schema, 'Membership'>;
export type MembershipDeleteArgs = $DeleteArgs<$Schema, 'Membership'>;
export type MembershipDeleteManyArgs = $DeleteManyArgs<$Schema, 'Membership'>;
export type MembershipCountArgs = $CountArgs<$Schema, 'Membership'>;
export type MembershipAggregateArgs = $AggregateArgs<$Schema, 'Membership'>;
export type MembershipGroupByArgs = $GroupByArgs<$Schema, 'Membership'>;
export type MembershipWhereInput = $WhereInput<$Schema, 'Membership'>;
export type MembershipSelect = $SelectInput<$Schema, 'Membership'>;
export type MembershipInclude = $IncludeInput<$Schema, 'Membership'>;
export type MembershipOmit = $OmitInput<$Schema, 'Membership'>;
export type MembershipGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Membership', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Membership', Args, Options>;
export type InviteFindManyArgs = $FindManyArgs<$Schema, 'Invite'>;
export type InviteFindUniqueArgs = $FindUniqueArgs<$Schema, 'Invite'>;
export type InviteFindFirstArgs = $FindFirstArgs<$Schema, 'Invite'>;
export type InviteExistsArgs = $ExistsArgs<$Schema, 'Invite'>;
export type InviteCreateArgs = $CreateArgs<$Schema, 'Invite'>;
export type InviteCreateManyArgs = $CreateManyArgs<$Schema, 'Invite'>;
export type InviteCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Invite'>;
export type InviteUpdateArgs = $UpdateArgs<$Schema, 'Invite'>;
export type InviteUpdateManyArgs = $UpdateManyArgs<$Schema, 'Invite'>;
export type InviteUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Invite'>;
export type InviteUpsertArgs = $UpsertArgs<$Schema, 'Invite'>;
export type InviteDeleteArgs = $DeleteArgs<$Schema, 'Invite'>;
export type InviteDeleteManyArgs = $DeleteManyArgs<$Schema, 'Invite'>;
export type InviteCountArgs = $CountArgs<$Schema, 'Invite'>;
export type InviteAggregateArgs = $AggregateArgs<$Schema, 'Invite'>;
export type InviteGroupByArgs = $GroupByArgs<$Schema, 'Invite'>;
export type InviteWhereInput = $WhereInput<$Schema, 'Invite'>;
export type InviteSelect = $SelectInput<$Schema, 'Invite'>;
export type InviteInclude = $IncludeInput<$Schema, 'Invite'>;
export type InviteOmit = $OmitInput<$Schema, 'Invite'>;
export type InviteGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Invite', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Invite', Args, Options>;
export type ApiKeyFindManyArgs = $FindManyArgs<$Schema, 'ApiKey'>;
export type ApiKeyFindUniqueArgs = $FindUniqueArgs<$Schema, 'ApiKey'>;
export type ApiKeyFindFirstArgs = $FindFirstArgs<$Schema, 'ApiKey'>;
export type ApiKeyExistsArgs = $ExistsArgs<$Schema, 'ApiKey'>;
export type ApiKeyCreateArgs = $CreateArgs<$Schema, 'ApiKey'>;
export type ApiKeyCreateManyArgs = $CreateManyArgs<$Schema, 'ApiKey'>;
export type ApiKeyCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ApiKey'>;
export type ApiKeyUpdateArgs = $UpdateArgs<$Schema, 'ApiKey'>;
export type ApiKeyUpdateManyArgs = $UpdateManyArgs<$Schema, 'ApiKey'>;
export type ApiKeyUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ApiKey'>;
export type ApiKeyUpsertArgs = $UpsertArgs<$Schema, 'ApiKey'>;
export type ApiKeyDeleteArgs = $DeleteArgs<$Schema, 'ApiKey'>;
export type ApiKeyDeleteManyArgs = $DeleteManyArgs<$Schema, 'ApiKey'>;
export type ApiKeyCountArgs = $CountArgs<$Schema, 'ApiKey'>;
export type ApiKeyAggregateArgs = $AggregateArgs<$Schema, 'ApiKey'>;
export type ApiKeyGroupByArgs = $GroupByArgs<$Schema, 'ApiKey'>;
export type ApiKeyWhereInput = $WhereInput<$Schema, 'ApiKey'>;
export type ApiKeySelect = $SelectInput<$Schema, 'ApiKey'>;
export type ApiKeyInclude = $IncludeInput<$Schema, 'ApiKey'>;
export type ApiKeyOmit = $OmitInput<$Schema, 'ApiKey'>;
export type ApiKeyGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ApiKey', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ApiKey', Args, Options>;
export type ApiKeyEnvironmentFindManyArgs = $FindManyArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentFindUniqueArgs = $FindUniqueArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentFindFirstArgs = $FindFirstArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentExistsArgs = $ExistsArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentCreateArgs = $CreateArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentCreateManyArgs = $CreateManyArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentUpdateArgs = $UpdateArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentUpdateManyArgs = $UpdateManyArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentUpsertArgs = $UpsertArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentDeleteArgs = $DeleteArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentDeleteManyArgs = $DeleteManyArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentCountArgs = $CountArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentAggregateArgs = $AggregateArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentGroupByArgs = $GroupByArgs<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentWhereInput = $WhereInput<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentSelect = $SelectInput<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentInclude = $IncludeInput<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentOmit = $OmitInput<$Schema, 'ApiKeyEnvironment'>;
export type ApiKeyEnvironmentGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ApiKeyEnvironment', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ApiKeyEnvironment', Args, Options>;
export type AccountFindManyArgs = $FindManyArgs<$Schema, 'Account'>;
export type AccountFindUniqueArgs = $FindUniqueArgs<$Schema, 'Account'>;
export type AccountFindFirstArgs = $FindFirstArgs<$Schema, 'Account'>;
export type AccountExistsArgs = $ExistsArgs<$Schema, 'Account'>;
export type AccountCreateArgs = $CreateArgs<$Schema, 'Account'>;
export type AccountCreateManyArgs = $CreateManyArgs<$Schema, 'Account'>;
export type AccountCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Account'>;
export type AccountUpdateArgs = $UpdateArgs<$Schema, 'Account'>;
export type AccountUpdateManyArgs = $UpdateManyArgs<$Schema, 'Account'>;
export type AccountUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Account'>;
export type AccountUpsertArgs = $UpsertArgs<$Schema, 'Account'>;
export type AccountDeleteArgs = $DeleteArgs<$Schema, 'Account'>;
export type AccountDeleteManyArgs = $DeleteManyArgs<$Schema, 'Account'>;
export type AccountCountArgs = $CountArgs<$Schema, 'Account'>;
export type AccountAggregateArgs = $AggregateArgs<$Schema, 'Account'>;
export type AccountGroupByArgs = $GroupByArgs<$Schema, 'Account'>;
export type AccountWhereInput = $WhereInput<$Schema, 'Account'>;
export type AccountSelect = $SelectInput<$Schema, 'Account'>;
export type AccountInclude = $IncludeInput<$Schema, 'Account'>;
export type AccountOmit = $OmitInput<$Schema, 'Account'>;
export type AccountGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Account', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Account', Args, Options>;
export type UserFindManyArgs = $FindManyArgs<$Schema, 'User'>;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, 'User'>;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, 'User'>;
export type UserExistsArgs = $ExistsArgs<$Schema, 'User'>;
export type UserCreateArgs = $CreateArgs<$Schema, 'User'>;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, 'User'>;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpdateArgs = $UpdateArgs<$Schema, 'User'>;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, 'User'>;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpsertArgs = $UpsertArgs<$Schema, 'User'>;
export type UserDeleteArgs = $DeleteArgs<$Schema, 'User'>;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, 'User'>;
export type UserCountArgs = $CountArgs<$Schema, 'User'>;
export type UserAggregateArgs = $AggregateArgs<$Schema, 'User'>;
export type UserGroupByArgs = $GroupByArgs<$Schema, 'User'>;
export type UserWhereInput = $WhereInput<$Schema, 'User'>;
export type UserSelect = $SelectInput<$Schema, 'User'>;
export type UserInclude = $IncludeInput<$Schema, 'User'>;
export type UserOmit = $OmitInput<$Schema, 'User'>;
export type UserGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'User', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'User', Args, Options>;
export type ShortUrlFindManyArgs = $FindManyArgs<$Schema, 'ShortUrl'>;
export type ShortUrlFindUniqueArgs = $FindUniqueArgs<$Schema, 'ShortUrl'>;
export type ShortUrlFindFirstArgs = $FindFirstArgs<$Schema, 'ShortUrl'>;
export type ShortUrlExistsArgs = $ExistsArgs<$Schema, 'ShortUrl'>;
export type ShortUrlCreateArgs = $CreateArgs<$Schema, 'ShortUrl'>;
export type ShortUrlCreateManyArgs = $CreateManyArgs<$Schema, 'ShortUrl'>;
export type ShortUrlCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ShortUrl'>;
export type ShortUrlUpdateArgs = $UpdateArgs<$Schema, 'ShortUrl'>;
export type ShortUrlUpdateManyArgs = $UpdateManyArgs<$Schema, 'ShortUrl'>;
export type ShortUrlUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ShortUrl'>;
export type ShortUrlUpsertArgs = $UpsertArgs<$Schema, 'ShortUrl'>;
export type ShortUrlDeleteArgs = $DeleteArgs<$Schema, 'ShortUrl'>;
export type ShortUrlDeleteManyArgs = $DeleteManyArgs<$Schema, 'ShortUrl'>;
export type ShortUrlCountArgs = $CountArgs<$Schema, 'ShortUrl'>;
export type ShortUrlAggregateArgs = $AggregateArgs<$Schema, 'ShortUrl'>;
export type ShortUrlGroupByArgs = $GroupByArgs<$Schema, 'ShortUrl'>;
export type ShortUrlWhereInput = $WhereInput<$Schema, 'ShortUrl'>;
export type ShortUrlSelect = $SelectInput<$Schema, 'ShortUrl'>;
export type ShortUrlInclude = $IncludeInput<$Schema, 'ShortUrl'>;
export type ShortUrlOmit = $OmitInput<$Schema, 'ShortUrl'>;
export type ShortUrlGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ShortUrl', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ShortUrl', Args, Options>;
export type SegmentFindManyArgs = $FindManyArgs<$Schema, 'Segment'>;
export type SegmentFindUniqueArgs = $FindUniqueArgs<$Schema, 'Segment'>;
export type SegmentFindFirstArgs = $FindFirstArgs<$Schema, 'Segment'>;
export type SegmentExistsArgs = $ExistsArgs<$Schema, 'Segment'>;
export type SegmentCreateArgs = $CreateArgs<$Schema, 'Segment'>;
export type SegmentCreateManyArgs = $CreateManyArgs<$Schema, 'Segment'>;
export type SegmentCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Segment'>;
export type SegmentUpdateArgs = $UpdateArgs<$Schema, 'Segment'>;
export type SegmentUpdateManyArgs = $UpdateManyArgs<$Schema, 'Segment'>;
export type SegmentUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Segment'>;
export type SegmentUpsertArgs = $UpsertArgs<$Schema, 'Segment'>;
export type SegmentDeleteArgs = $DeleteArgs<$Schema, 'Segment'>;
export type SegmentDeleteManyArgs = $DeleteManyArgs<$Schema, 'Segment'>;
export type SegmentCountArgs = $CountArgs<$Schema, 'Segment'>;
export type SegmentAggregateArgs = $AggregateArgs<$Schema, 'Segment'>;
export type SegmentGroupByArgs = $GroupByArgs<$Schema, 'Segment'>;
export type SegmentWhereInput = $WhereInput<$Schema, 'Segment'>;
export type SegmentSelect = $SelectInput<$Schema, 'Segment'>;
export type SegmentInclude = $IncludeInput<$Schema, 'Segment'>;
export type SegmentOmit = $OmitInput<$Schema, 'Segment'>;
export type SegmentGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Segment', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Segment', Args, Options>;
export type LanguageFindManyArgs = $FindManyArgs<$Schema, 'Language'>;
export type LanguageFindUniqueArgs = $FindUniqueArgs<$Schema, 'Language'>;
export type LanguageFindFirstArgs = $FindFirstArgs<$Schema, 'Language'>;
export type LanguageExistsArgs = $ExistsArgs<$Schema, 'Language'>;
export type LanguageCreateArgs = $CreateArgs<$Schema, 'Language'>;
export type LanguageCreateManyArgs = $CreateManyArgs<$Schema, 'Language'>;
export type LanguageCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Language'>;
export type LanguageUpdateArgs = $UpdateArgs<$Schema, 'Language'>;
export type LanguageUpdateManyArgs = $UpdateManyArgs<$Schema, 'Language'>;
export type LanguageUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Language'>;
export type LanguageUpsertArgs = $UpsertArgs<$Schema, 'Language'>;
export type LanguageDeleteArgs = $DeleteArgs<$Schema, 'Language'>;
export type LanguageDeleteManyArgs = $DeleteManyArgs<$Schema, 'Language'>;
export type LanguageCountArgs = $CountArgs<$Schema, 'Language'>;
export type LanguageAggregateArgs = $AggregateArgs<$Schema, 'Language'>;
export type LanguageGroupByArgs = $GroupByArgs<$Schema, 'Language'>;
export type LanguageWhereInput = $WhereInput<$Schema, 'Language'>;
export type LanguageSelect = $SelectInput<$Schema, 'Language'>;
export type LanguageInclude = $IncludeInput<$Schema, 'Language'>;
export type LanguageOmit = $OmitInput<$Schema, 'Language'>;
export type LanguageGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Language', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Language', Args, Options>;
export type SurveyLanguageFindManyArgs = $FindManyArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageFindUniqueArgs = $FindUniqueArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageFindFirstArgs = $FindFirstArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageExistsArgs = $ExistsArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageCreateArgs = $CreateArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageCreateManyArgs = $CreateManyArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageUpdateArgs = $UpdateArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageUpdateManyArgs = $UpdateManyArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageUpsertArgs = $UpsertArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageDeleteArgs = $DeleteArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageDeleteManyArgs = $DeleteManyArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageCountArgs = $CountArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageAggregateArgs = $AggregateArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageGroupByArgs = $GroupByArgs<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageWhereInput = $WhereInput<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageSelect = $SelectInput<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageInclude = $IncludeInput<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageOmit = $OmitInput<$Schema, 'SurveyLanguage'>;
export type SurveyLanguageGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'SurveyLanguage', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SurveyLanguage', Args, Options>;
export type InsightFindManyArgs = $FindManyArgs<$Schema, 'Insight'>;
export type InsightFindUniqueArgs = $FindUniqueArgs<$Schema, 'Insight'>;
export type InsightFindFirstArgs = $FindFirstArgs<$Schema, 'Insight'>;
export type InsightExistsArgs = $ExistsArgs<$Schema, 'Insight'>;
export type InsightCreateArgs = $CreateArgs<$Schema, 'Insight'>;
export type InsightCreateManyArgs = $CreateManyArgs<$Schema, 'Insight'>;
export type InsightCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Insight'>;
export type InsightUpdateArgs = $UpdateArgs<$Schema, 'Insight'>;
export type InsightUpdateManyArgs = $UpdateManyArgs<$Schema, 'Insight'>;
export type InsightUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Insight'>;
export type InsightUpsertArgs = $UpsertArgs<$Schema, 'Insight'>;
export type InsightDeleteArgs = $DeleteArgs<$Schema, 'Insight'>;
export type InsightDeleteManyArgs = $DeleteManyArgs<$Schema, 'Insight'>;
export type InsightCountArgs = $CountArgs<$Schema, 'Insight'>;
export type InsightAggregateArgs = $AggregateArgs<$Schema, 'Insight'>;
export type InsightGroupByArgs = $GroupByArgs<$Schema, 'Insight'>;
export type InsightWhereInput = $WhereInput<$Schema, 'Insight'>;
export type InsightSelect = $SelectInput<$Schema, 'Insight'>;
export type InsightInclude = $IncludeInput<$Schema, 'Insight'>;
export type InsightOmit = $OmitInput<$Schema, 'Insight'>;
export type InsightGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Insight', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Insight', Args, Options>;
export type DocumentInsightFindManyArgs = $FindManyArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightFindUniqueArgs = $FindUniqueArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightFindFirstArgs = $FindFirstArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightExistsArgs = $ExistsArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightCreateArgs = $CreateArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightCreateManyArgs = $CreateManyArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightUpdateArgs = $UpdateArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightUpdateManyArgs = $UpdateManyArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightUpsertArgs = $UpsertArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightDeleteArgs = $DeleteArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightDeleteManyArgs = $DeleteManyArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightCountArgs = $CountArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightAggregateArgs = $AggregateArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightGroupByArgs = $GroupByArgs<$Schema, 'DocumentInsight'>;
export type DocumentInsightWhereInput = $WhereInput<$Schema, 'DocumentInsight'>;
export type DocumentInsightSelect = $SelectInput<$Schema, 'DocumentInsight'>;
export type DocumentInsightInclude = $IncludeInput<$Schema, 'DocumentInsight'>;
export type DocumentInsightOmit = $OmitInput<$Schema, 'DocumentInsight'>;
export type DocumentInsightGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'DocumentInsight', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'DocumentInsight', Args, Options>;
export type DocumentFindManyArgs = $FindManyArgs<$Schema, 'Document'>;
export type DocumentFindUniqueArgs = $FindUniqueArgs<$Schema, 'Document'>;
export type DocumentFindFirstArgs = $FindFirstArgs<$Schema, 'Document'>;
export type DocumentExistsArgs = $ExistsArgs<$Schema, 'Document'>;
export type DocumentCreateArgs = $CreateArgs<$Schema, 'Document'>;
export type DocumentCreateManyArgs = $CreateManyArgs<$Schema, 'Document'>;
export type DocumentCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Document'>;
export type DocumentUpdateArgs = $UpdateArgs<$Schema, 'Document'>;
export type DocumentUpdateManyArgs = $UpdateManyArgs<$Schema, 'Document'>;
export type DocumentUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Document'>;
export type DocumentUpsertArgs = $UpsertArgs<$Schema, 'Document'>;
export type DocumentDeleteArgs = $DeleteArgs<$Schema, 'Document'>;
export type DocumentDeleteManyArgs = $DeleteManyArgs<$Schema, 'Document'>;
export type DocumentCountArgs = $CountArgs<$Schema, 'Document'>;
export type DocumentAggregateArgs = $AggregateArgs<$Schema, 'Document'>;
export type DocumentGroupByArgs = $GroupByArgs<$Schema, 'Document'>;
export type DocumentWhereInput = $WhereInput<$Schema, 'Document'>;
export type DocumentSelect = $SelectInput<$Schema, 'Document'>;
export type DocumentInclude = $IncludeInput<$Schema, 'Document'>;
export type DocumentOmit = $OmitInput<$Schema, 'Document'>;
export type DocumentGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Document', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Document', Args, Options>;
export type TeamFindManyArgs = $FindManyArgs<$Schema, 'Team'>;
export type TeamFindUniqueArgs = $FindUniqueArgs<$Schema, 'Team'>;
export type TeamFindFirstArgs = $FindFirstArgs<$Schema, 'Team'>;
export type TeamExistsArgs = $ExistsArgs<$Schema, 'Team'>;
export type TeamCreateArgs = $CreateArgs<$Schema, 'Team'>;
export type TeamCreateManyArgs = $CreateManyArgs<$Schema, 'Team'>;
export type TeamCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Team'>;
export type TeamUpdateArgs = $UpdateArgs<$Schema, 'Team'>;
export type TeamUpdateManyArgs = $UpdateManyArgs<$Schema, 'Team'>;
export type TeamUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Team'>;
export type TeamUpsertArgs = $UpsertArgs<$Schema, 'Team'>;
export type TeamDeleteArgs = $DeleteArgs<$Schema, 'Team'>;
export type TeamDeleteManyArgs = $DeleteManyArgs<$Schema, 'Team'>;
export type TeamCountArgs = $CountArgs<$Schema, 'Team'>;
export type TeamAggregateArgs = $AggregateArgs<$Schema, 'Team'>;
export type TeamGroupByArgs = $GroupByArgs<$Schema, 'Team'>;
export type TeamWhereInput = $WhereInput<$Schema, 'Team'>;
export type TeamSelect = $SelectInput<$Schema, 'Team'>;
export type TeamInclude = $IncludeInput<$Schema, 'Team'>;
export type TeamOmit = $OmitInput<$Schema, 'Team'>;
export type TeamGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'Team', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Team', Args, Options>;
export type TeamUserFindManyArgs = $FindManyArgs<$Schema, 'TeamUser'>;
export type TeamUserFindUniqueArgs = $FindUniqueArgs<$Schema, 'TeamUser'>;
export type TeamUserFindFirstArgs = $FindFirstArgs<$Schema, 'TeamUser'>;
export type TeamUserExistsArgs = $ExistsArgs<$Schema, 'TeamUser'>;
export type TeamUserCreateArgs = $CreateArgs<$Schema, 'TeamUser'>;
export type TeamUserCreateManyArgs = $CreateManyArgs<$Schema, 'TeamUser'>;
export type TeamUserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'TeamUser'>;
export type TeamUserUpdateArgs = $UpdateArgs<$Schema, 'TeamUser'>;
export type TeamUserUpdateManyArgs = $UpdateManyArgs<$Schema, 'TeamUser'>;
export type TeamUserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'TeamUser'>;
export type TeamUserUpsertArgs = $UpsertArgs<$Schema, 'TeamUser'>;
export type TeamUserDeleteArgs = $DeleteArgs<$Schema, 'TeamUser'>;
export type TeamUserDeleteManyArgs = $DeleteManyArgs<$Schema, 'TeamUser'>;
export type TeamUserCountArgs = $CountArgs<$Schema, 'TeamUser'>;
export type TeamUserAggregateArgs = $AggregateArgs<$Schema, 'TeamUser'>;
export type TeamUserGroupByArgs = $GroupByArgs<$Schema, 'TeamUser'>;
export type TeamUserWhereInput = $WhereInput<$Schema, 'TeamUser'>;
export type TeamUserSelect = $SelectInput<$Schema, 'TeamUser'>;
export type TeamUserInclude = $IncludeInput<$Schema, 'TeamUser'>;
export type TeamUserOmit = $OmitInput<$Schema, 'TeamUser'>;
export type TeamUserGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'TeamUser', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'TeamUser', Args, Options>;
export type ProjectTeamFindManyArgs = $FindManyArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamFindUniqueArgs = $FindUniqueArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamFindFirstArgs = $FindFirstArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamExistsArgs = $ExistsArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamCreateArgs = $CreateArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamCreateManyArgs = $CreateManyArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamUpdateArgs = $UpdateArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamUpdateManyArgs = $UpdateManyArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamUpsertArgs = $UpsertArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamDeleteArgs = $DeleteArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamDeleteManyArgs = $DeleteManyArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamCountArgs = $CountArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamAggregateArgs = $AggregateArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamGroupByArgs = $GroupByArgs<$Schema, 'ProjectTeam'>;
export type ProjectTeamWhereInput = $WhereInput<$Schema, 'ProjectTeam'>;
export type ProjectTeamSelect = $SelectInput<$Schema, 'ProjectTeam'>;
export type ProjectTeamInclude = $IncludeInput<$Schema, 'ProjectTeam'>;
export type ProjectTeamOmit = $OmitInput<$Schema, 'ProjectTeam'>;
export type ProjectTeamGetPayload<
    Args extends $SelectIncludeOmit<$Schema, 'ProjectTeam', true>,
    Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ProjectTeam', Args, Options>;
