import fs from 'node:fs';
import path from 'node:path';
import { generateMigrateBody } from './codegen';
import type { SchemaChange } from './diff';
import { serializeSnapshot } from './snapshot';
import type { Snapshot } from './types';

export interface MigrationFolderInput {
    /** Absolute path of the migration folder to create. */
    dir: string;
    changes: SchemaChange[];
    /** Snapshot representing the schema state *after* this migration. */
    after: Snapshot;
}

/**
 * Writes a migration folder:
 *  - `snapshot.json` — the (stable) schema snapshot after this migration
 *  - `migration.ts`  — the `migrate` function
 */
export function writeMigrationFolder(input: MigrationFolderInput): void {
    fs.mkdirSync(input.dir, { recursive: true });
    fs.writeFileSync(path.join(input.dir, 'snapshot.json'), serializeSnapshot(input.after));
    fs.writeFileSync(path.join(input.dir, 'migration.ts'), renderMigrationFile(input.changes, input.after));
}

function renderMigrationFile(changes: SchemaChange[], after: Snapshot): string {
    const body = generateMigrateBody(changes, after.provider, after);
    const migrateBody = body.trim().length > 0 ? body : '    // no schema changes';
    const usesSql = migrateBody.includes('sql`');
    const sqlImport = usesSql ? `\nimport { sql } from 'kysely';` : '';

    return `// Generated by ZenStack migration engine.
import type { Kysely } from 'kysely';${sqlImport}

/**
 * Applies this migration. Use the Kysely \`db\` for both schema (DDL) changes and any custom
 * data transformations (e.g. backfills) — edit the body below as needed.
 */
export async function migrate(db: Kysely<any>): Promise<void> {
${migrateBody}
}
`;
}
