name: Update Samples

on:
    release:
        types: [published]

jobs:
    dispatch:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                repo:
                    [
                        'zenstackhq/sample-todo-nextjs',
                        'zenstackhq/sample-todo-nextjs-tanstack',
                        'zenstackhq/sample-todo-trpc',
                        'zenstackhq/sample-todo-sveltekit',
                        'zenstackhq/sample-todo-nuxt',
                    ]

        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v3.0.0
              with:
                  token: ${{ secrets.RELEASE_TRIGGER_TOKEN }}
                  repository: ${{ matrix.repo }}
                  event-type: zenstack-release
